name: Assemble Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: github
      GOPRIVATE: "github.com/lucidcube/*,github.com/LucidCube/*,github.com/chargehive/*"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: |
          go build -v ./...

      - name: Test
        run: go test -v ./...
